sudo: required
services:
- docker

before_install:
- docker build -t palerique/multi-docker -f ./client/Dockerfile.dev .

script:
- docker run palerique/multi-docker npm run test -- --coverage

after_success:
- docker build -t palerique/multi-docker-client ./client
- docker build -t palerique/multi-docker-nginx ./nginx
- docker build -t palerique/multi-docker-server ./server
- docker build -t palerique/multi-docker-worker ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push palerique/multi-docker-client
- docker push palerique/multi-docker-nginx
- docker push palerique/multi-docker-server
- docker push palerique/multi-docker-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "multi-docker-udemy"
#  env: "MultiDocker-env"
#  bucket_name: "elasticbeanstalk-us-east-1-799098231639"
#  bucket_path: "multi-docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"